version: '3'

services:
  app:
    image: 'bizone_test:latest'
    build:
      context: .
    container_name: api
    ports:
      - "8080:8080"
      - "9999:9999"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASS=some_secure_password
      - DB_NAME=bizone
      - LD_LIBRARY_PATH=/app/utils
      - TOKEN_PASSWORD=thisIsTheJwtSecretPassword

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: some_secure_password
      POSTGRES_DB: bizone
    volumes:
      - postgres2:/var/lib/postgresql/data

volumes:
  postgres2: